const myData = [
  {
    key: 1,
    name: 'CBSE : Class X',
    objective: '10 Completion  ,6 Review',
    task: 1200,
    venders: 'Crystal Edtech',
    members: '/images/first.svg',
    subjects: 'Physics, Math, History',
  },
  {
    key: 2,
    name: 'ICSE : Class X',
    objective: '6 Review',
    task: 1400,
    venders: 'Crystal Edtech ; FD...',
    members: '/images/second.svg',
    subjects: 'Physics',
  },
  {
    key: 3,
    name: 'ISC : Class XI',
    objective: '21 Completion  ,12 Review',
    task: 22000,
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '- -',
    subjects: 'Mathematics',
  },
  {
    key: 4,
    name: 'IIT-JEE (PCMB)',
    objective: '10 Completion',
    task: 1200,
    venders: 'FDT Vendors',
    members: '/images/third.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 5,
    name: 'IIT-JEE',
    objective: '25 Completion',
    task: 1400,
    venders: 'SMART Pvt. Ltd.',
    members: '/images/fourth.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 6,
    name: 'IIT-JEE',
    objective: '- - ',
    task: 5000,
    venders: '- -',
    members: '/images/fifth.svg',
    subjects: 'History, Pol. Science',
  },
  {
    key: 7,
    name: 'IIT-JEE',
    objective: '- - ',
    task: '- -',
    venders: '- -',
    members: '/images/sixth.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 8,
    name: 'IIT-JEE (PCMB)',
    objective: '20 Completion  ,14 Review',
    task: '1400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 9,
    name: 'IIT-JEE',
    objective: '- -',
    task: '2000',
    venders: '- -',
    members: '/images/eight.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 10,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 11,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 12,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 13,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 14,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 1,
    name: 'CBSE : Class X',
    objective: '10 Completion  ,6 Review',
    task: 1200,
    venders: 'Crystal Edtech',
    members: '/images/first.svg',
    subjects: 'Physics, Math, History',
  },
  {
    key: 2,
    name: 'ICSE : Class X',
    objective: '6 Review',
    task: 1400,
    venders: 'Crystal Edtech ; FD...',
    members: '/images/second.svg',
    subjects: 'Physics',
  },
  {
    key: 3,
    name: 'ISC : Class XI',
    objective: '21 Completion  ,12 Review',
    task: 22000,
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '- -',
    subjects: 'Mathematics',
  },
  {
    key: 4,
    name: 'IIT-JEE (PCMB)',
    objective: '10 Completion',
    task: 1200,
    venders: 'FDT Vendors',
    members: '/images/third.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 5,
    name: 'IIT-JEE',
    objective: '25 Completion',
    task: 1400,
    venders: 'SMART Pvt. Ltd.',
    members: '/images/fourth.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 6,
    name: 'IIT-JEE',
    objective: '- - ',
    task: 5000,
    venders: '- -',
    members: '/images/fifth.svg',
    subjects: 'History, Pol. Science',
  },
  {
    key: 7,
    name: 'IIT-JEE',
    objective: '- - ',
    task: '- -',
    venders: '- -',
    members: '/images/sixth.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 8,
    name: 'IIT-JEE (PCMB)',
    objective: '20 Completion  ,14 Review',
    task: '1400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 9,
    name: 'IIT-JEE',
    objective: '- -',
    task: '2000',
    venders: '- -',
    members: '/images/eight.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 10,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 11,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 12,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 13,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 14,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 1,
    name: 'CBSE : Class X',
    objective: '10 Completion  ,6 Review',
    task: 1200,
    venders: 'Crystal Edtech',
    members: '/images/first.svg',
    subjects: 'Physics, Math, History',
  },
  {
    key: 2,
    name: 'ICSE : Class X',
    objective: '6 Review',
    task: 1400,
    venders: 'Crystal Edtech ; FD...',
    members: '/images/second.svg',
    subjects: 'Physics',
  },
  {
    key: 3,
    name: 'ISC : Class XI',
    objective: '21 Completion  ,12 Review',
    task: 22000,
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '- -',
    subjects: 'Mathematics',
  },
  {
    key: 4,
    name: 'IIT-JEE (PCMB)',
    objective: '10 Completion',
    task: 1200,
    venders: 'FDT Vendors',
    members: '/images/third.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 5,
    name: 'IIT-JEE',
    objective: '25 Completion',
    task: 1400,
    venders: 'SMART Pvt. Ltd.',
    members: '/images/fourth.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 6,
    name: 'IIT-JEE',
    objective: '- - ',
    task: 5000,
    venders: '- -',
    members: '/images/fifth.svg',
    subjects: 'History, Pol. Science',
  },
  {
    key: 7,
    name: 'IIT-JEE',
    objective: '- - ',
    task: '- -',
    venders: '- -',
    members: '/images/sixth.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 8,
    name: 'IIT-JEE (PCMB)',
    objective: '20 Completion  ,14 Review',
    task: '1400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 9,
    name: 'IIT-JEE',
    objective: '- -',
    task: '2000',
    venders: '- -',
    members: '/images/eight.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 10,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 11,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 12,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 13,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 14,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 1,
    name: 'CBSE : Class X',
    objective: '10 Completion  ,6 Review',
    task: 1200,
    venders: 'Crystal Edtech',
    members: '/images/first.svg',
    subjects: 'Physics, Math, History',
  },
  {
    key: 2,
    name: 'ICSE : Class X',
    objective: '6 Review',
    task: 1400,
    venders: 'Crystal Edtech ; FD...',
    members: '/images/second.svg',
    subjects: 'Physics',
  },
  {
    key: 3,
    name: 'ISC : Class XI',
    objective: '21 Completion  ,12 Review',
    task: 22000,
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '- -',
    subjects: 'Mathematics',
  },
  {
    key: 4,
    name: 'IIT-JEE (PCMB)',
    objective: '10 Completion',
    task: 1200,
    venders: 'FDT Vendors',
    members: '/images/third.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 5,
    name: 'IIT-JEE',
    objective: '25 Completion',
    task: 1400,
    venders: 'SMART Pvt. Ltd.',
    members: '/images/fourth.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 6,
    name: 'IIT-JEE',
    objective: '- - ',
    task: 5000,
    venders: '- -',
    members: '/images/fifth.svg',
    subjects: 'History, Pol. Science',
  },
  {
    key: 7,
    name: 'IIT-JEE',
    objective: '- - ',
    task: '- -',
    venders: '- -',
    members: '/images/sixth.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 8,
    name: 'IIT-JEE (PCMB)',
    objective: '20 Completion  ,14 Review',
    task: '1400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 9,
    name: 'IIT-JEE',
    objective: '- -',
    task: '2000',
    venders: '- -',
    members: '/images/eight.svg',
    subjects: 'Physics, Maths, Chemistry',
  },
  {
    key: 10,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 11,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 12,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 13,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 14,
    name: 'IIT-JEE (PCMB)',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
  {
    key: 14,
    name: 'HINDI',
    objective: '6 Review',
    task: '400',
    venders: 'Teacher’s Global Pvt. Ltd.',
    members: '/images/nine.svg',
    subjects: 'Physics, Maths, +2 more',
  },
];

export { myData };
